---
- hosts: dns
  remote_user: root

  vars_files:
    - "secrets/{{ inventory_hostname }}.yml"

  tasks:
    - name: Update and upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: safe
      tags:
        - installation
        - packages

    - name: Install of BIND packages
      ansible.builtin.apt:
        state: latest
        pkg:
          - bind9
          - bind9-host
          - bind9utils
          - dnsutils
      tags:
        - installation
        - packages

    - name: Display the dns_zones
      debug:
        var: dns_zones
      tags:
        - debug
      when:
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_refresh
      tags:
        - debug
      when:
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_retry
      tags:
        - debug
      when:
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_expire
      tags:
        - debug
      when:
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_negativ_ttl
      tags:
        - debug
      when:
        - debug_vars

    - name: Create directory for log fies
      ansible.builtin.file:
        state: directory
        path: /var/log/named
        mode: '0774'
        owner: bind
        group: bind
      tags:
        - installation
        - configuration

    - name: Create Log files
      ansible.builtin.file:
        group: bind
        owner: bind
        state: touch
        mode: '0660'
        path: "{{ item }}"
      with_items:
        - /var/log/named/default.log
        - /var/log/named/general.log
        - /var/log/named/database.log
        - /var/log/named/security.log
        - /var/log/named/config.log
        - /var/log/named/resolver.log
        - /var/log/named/xfer-in.log
        - /var/log/named/xfer-out.log
        - /var/log/named/notify.log
        - /var/log/named/client.log
        - /var/log/named/unmatched.log
        - /var/log/named/queries.log
        - /var/log/named/network.log
        - /var/log/named/update.log
        - /var/log/named/dispatch.log
        - /var/log/named/dnssec.log
        - /var/log/named/lame-servers.log
      tags:
        - installation
        - configurationa

    - name: Deploy named.conf.options
      ansible.builtin.template:
        src: dns/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
      notify:
        - Restart bind
      tags:
        - configuration


    - name: Deploy named.conf.local
      ansible.builtin.template:
        src: dns/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'
      notify:
        - Restart bind
      tags:
        - configuration


    - name: Deploy individual zone files
      ansible.builtin.template:
        src: dns/zonefile-master-{{ item.zonefile }}.j2
        dest: "/var/cache/bind/db.{{ item.name }}"
        owner: root
        group: bind
        mode: '0644'
      with_items: "{{ dns_zones }}"
      when:
        - item.type == "master"
      notify:
        - Restart bind
      tags:
        - configuration
        - zonefiles

    - name: Test zone files with named-checkzone
      ansible.builtin.shell:
        chdir: /var/cache/bind/
        cmd: named-checkzone {{ item.name }} /var/cache/bind/db.{{ item.name }}
      with_items: "{{ dns_zones }}"
      register: dns_check_results
      tags:
        - test
        - zonefiles

    - ansible.builtin.debug:
        var: dns_check_results
      tags:
        - test
        - zonefiles

    - ansible.builtin.debug:
        msg: "Zonefile check completet with: {{ dns_check_results.msg }}"
      tags:
        - test
        - zonefiles

    - ansible.builtin.debug:
        msg:
          - "DNS Zone: '{{ item.item.name }}'"
          - "Error: "
          - "{{ item.stderr }}"
      with_items: "{{ dns_check_results.results }}"
      when:
        - item.rc != 0
      tags:
        - test
        - zonefiles

  handlers:
    - name: Restart bind
      ansible.builtin.service:
        name: bind9
        state: restarted
