---
- hosts: dns 
  remote_user: root 

  tasks: 
    - name: Update and upgrade system 
      ansible.builtin.apt:
        update_cache: yes 
        upgrade: safe
      tags:
        - installation
      
    - name: Install of BIND packages 
      ansible.builtin.apt: 
        state: latest 
        pkg:
          - bind9
          - bind9-host
          - bind9utils
          - dnsutils
      tags: 
        - installation

    - name: Create directory for log fies 
      ansible.builtin.file:
        state: directory 
        path: /var/log/bind
        mode: '0744' 
        owner: bind
        group: bind 
      tags:
        - installation
        - configuration

    - name: Display the dns_zones 
      debug:
        var: dns_zones 
      tags:
        - debug 
      when: 
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_refresh
      tags:
        - debug 
      when: 
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_retry
      tags:
        - debug     
      when: 
        - debug_vars 
    - name: Debug default variables
      debug:
        var: dns_default_expire
      tags:
        - debug 
      when: 
        - debug_vars
    - name: Debug default variables
      debug:
        var: dns_default_negativ_ttl
      tags:
        - debug  
      when: 
        - debug_vars 

    - name: Deploy named.conf.options 
      ansible.builtin.template: 
        src: dns/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root 
        group: bind  
        mode: '0644'
      tags:
        - configuration 

    - name: Deploy named.conf.local 
      ansible.builtin.template:
        src: dns/named.conf.local.j2 
        dest: /etc/bind/named.conf.local
        owner: root 
        group: bind 
        mode: '0644'
      tags:
        - configuration

    - name: Deploy individual zone files
      ansible.builtin.template:
        src: dns/zonefile-master.j2 
        dest: "/var/cache/bind/db.{{ item.name }}"
        owner: root 
        group: bind 
        mode: '0644'
      with_items: "{{ dns_zones }}"
      tags:
        - configuration
        - zonefiles

