---
- hosts: mailcow
  remote_user: root

  tasks:
    - name: Update and upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: safe
      tags:
        - installation
        - packages

    - name: Debug message as placeholder instead of the preparation steps
      ansible.builtin.debug:
        msg: "Ansible Play for preparing the host with Docker and Docker-Compose. Needs to be tested on another host"

    # - name: Install packages
    #   ansible.builtin.apt:
    #     state: latest
    #     pkg:
    #       - ca-certificates
    #       - curl
    #       - gnupg
    #       - lsb-release
    #       - git
    #   tags:
    #     - installation
    #     - packages

    # - name: Add Docker GPG Key
    #   ansible.builtin.apt_key:
    #     url: https://download.docker.com/linux/debian/gpg
    #     state: present
    # - name: Add Docker Repository (Bullseye)
    #   ansible.builtin.apt_repository:
    #     repo: deb https://download.docker.com/linux/debian bullseye stable
    #     state: present
    #     filename: docker-ce

    # - name: Install docker from source
    #   ansible.builtin.shell:
    #     cmd: curl -sSL https://get.docker.com/ | CHANNEL=stable sh

    # - name: Enable and Active Docker Service
    #   ansible.builtin.service:
    #     name: docker
    #     enabled: yes
    #     state: started

    # - name: Download and install docker-compose
    #   ansible.builtin.shell:
    #     cmd: curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
    # - name: Make docker-compose executable
    #   ansible.builtin.file:
    #     path: /usr/local/bin/docker-compose
    #     mode: 0744
    #     state: file

- hosts: mailcow
  remote_user: root

  # roles:
  #  - mailcow.mailcow_ansiblerole

  tasks:
    - ansible.builtin.debug:
        msg: "Mailcow Role would be used instead of this debug message"
