---
- name: Install Dockerized Bitwarden
  hosts: docker
  remote_user: root

  vars_files:
    - "secrets/{{ inventory_hostname }}.yml"

  tasks:
    - name: Create Bitwarden directory
      ansible.builtin.file:
        owner: root
        group: root
        mode: '0775'
        state: directory
        path: /opt/docker/bitwarden

    - name: Create data directory
      ansible.builtin.file:
        owner: root
        group: root
        mode: '0775'
        state: directory
        path: /opt/docker/bitwarden/data

    - name: Deploy the Bitwarden docker-compose.yml
      ansible.builtin.template:
        src: docker/bitwarden/docker-compose.yml.j2
        dest: /opt/docker/bitwarden/docker-compose.yml
        owner: root
        group: root
        mode: '0664'

    - name: Run Bitwarden docker compose
      shell:
        cmd: "docker compose up -d --force-recreate"
        chdir: /opt/docker/bitwarden
